import { dateImages } from "src/constants/images";

import { EventDate } from "./types";

export const allDates: EventDate[] = [
  {
    id: "KPL",
    type: "KPL",
    title: "Catholic Ceremony",
    when: "November 7, 2025",
    dateVertical: "<span>11</span><br/><span class='month'>07</span><br/><span>25</span>",
    time: "12:00 PM",
    place: "Dress code: Formal wear",
    vendorName: "St. Pius X Catholic Church",
    mapLink: "https://maps.app.goo.gl/oYPVyFcugnyiTmYQA",
    dresscode: "",
    note: "",
    note_1:"Bus Transportation to Church 11:00 AM",
    note_2:"Location: Near Entrance of the Hilton",
    note_3:"",
    note_4:"",
    images: dateImages.kpl,
    whenDate: "07",
    whenMonth: "Nov",
    rawDate: {
      startDate: "2025-11-07",
      startTime: "12:00",
      endTime: "13:00",
    },
  },
  {
    id: "SNG_RSV",
    type: "SNG",
    title: "Welcome Party (Sangeet)",
    when: "November 7, 2025",
    dateVertical: "<span>07</span><br/><span class='month'>11</span><br/><span>25</span>",
    time: "6:00 PM",
    place: "Dress code: Semi-formal or Indo-western",
    vendorName: "Beach House Fort Lauderdale, A Hilton Resort (Balqony)",
    mapLink: "https://maps.app.goo.gl/Toty2d4kykeN9MpS8",
    dresscode: "",
    note: "",
    note_1:"",
    note_2:"",
    note_3:"",
    note_4:"",
    images: dateImages.sng,
    whenDate: "07",
    whenMonth: "Nov",
    rawDate: {
      startDate: "2025-11-07",
      startTime: "18:00",
      endTime: "22:00",
    },
  },
  {
    id: "KPL_RSV",
    type: "KPL",
    title: "Hindu Ceremony",
    when: "November 8, 2025",
    dateVertical:
        "<span>08</span><br/><span class='month'>11</span><br/><span>25</span>",
    time: "12:00 PM",
    place: "Dress code: Indian or Light Formalwear",
    vendorName:"Beach House Fort Lauderdale, A Hilton Resort (Balqony)",
    mapLink: "https://maps.app.goo.gl/Toty2d4kykeN9MpS8",
    dresscode: "",
    note: "",
    note_1:"Baraat 12:00pm",
    note_2:"Hindu Ceremony 1:30pm-3:30pm",
    note_3:"Cocktail Hour 5:00pm-6:00pm",
    note_4:"",

    images: dateImages.kplrsp,
    whenDate: "08",
    whenMonth: "Nov",
    rawDate: {
      startDate: "2025-11-08",
      startTime: "14:00",
      endTime: "18:00",
    },
  },
  {
    id: "BHM_RSV",
    type: "BHM",
    title: "Reception",
    when: "November 8, 2025",
    dateVertical: "<span>08</span><br/><span class='month'>11</span><br/><span>25</span>",
    time: "6:00 PM",
    place: "Dress code: Cocktail, formal wear",
    vendorName: "Beach House Fort Lauderdale, A Hilton Resort (Del Sol Ballroom)",
    mapLink: "https://maps.app.goo.gl/Toty2d4kykeN9MpS8",
    dresscode: "",
    note: "",
    note_1:"",
    note_2:"",
    note_3:"",
    note_4:"",
    images: dateImages.bhm,
    whenDate: "08",
    whenMonth: "Nov",
    rawDate: {
      startDate: "2025-11-08",
      startTime: "18:00",
      endTime: "22:00",
    },
  },
];
